### PR TITLE
Dc strato

### PR DESCRIPTION
**Pull request by DCStrato**
New Monitor.htm file is being updated in the directory with songs.  This can be installed in a OBS Browser dock to monitor Current Song: Current Lyric: Next Lyric: and Next Song:

### CODE REVIEW

**Comment by amirchev** [comment]
Hey, would it possible to update the Readme to explain how to use the monitor.htm file? Also, instead of having two .lua files, could you leave only the one that you think is best?

**Comment by DCStrato** [comment]
Yes to both

**Comment by amirchev** [comment]
Hey, the lyrics text keeps blinking while using this file. Everything works fine but the crossfade. :(

**Comment by amirchev** [comment]
I did a little digging through the commit history of your #22 pull request. I found that this commit: ee87469c148039a6966b26901c93628ed9bdf517 actually works as expected. Somewhere down the line, the code was ruined and created the blinking when paging bug again. Maybe if you revert to that commit and make the changes again, we'll be ok?

**Comment by DCStrato** [comment]
Ok I will check it out.  Thanks

**Comment by DCStrato** [comment]
I am planning to use this version in service tomorrow.  Hopefully all will go well, but nothing like going live to find issues!   

If your configurations all work in addition to mine, we might be good.  I have a large inventory of song lyrics I might contribute as examples that could download with the code.  I will go over each early next week and confirm they all still work.

**Comment by amirchev** [comment]
Hey @wzaggle, I did a test run and noticed that if you hide the lyrics using the "Hide/Show Lyrics" button, you cannot unhide them using that button. You have to press "Next lyric" button and then lyrics will show.

**Comment by amirchev** [comment]
I looked a little through it but am having a hard time following the code :(

**Comment by DCStrato** [comment]
Every time I get back to the Lyrics Code it takes me a few hours to figure it out again.  It is a big mental model for how it all works.  Cleaner now than before. Some things were working because of what were really bugs. Mostly the fade options working with non-fade, and source loads working with pre-prepared lists.   

 

I believe I got the show/hide fixed as long as it didn’t break something else, which is what typically happens.  

 

WZ

**Pull request merged**
